### ISSUE TITLE
eww or xwidgets support

### ISSUE THREAD

**Issue by fbob** [honmaple/emacs-maple-preview#5]
I was wondering if an all in one solution could be feasible with eww or xwidgets preview in emacs without using an external browser. 
What do you think of an option to choose the browser: either via emacs or an external one?

**Comment by honmaple** [comment]
`maple-preview` uses websocket to preview realtime, unfortunately, eww doesn't support javescript.  

Xwidgets is a great way to preview,and it's easy to custom your brower https://www.emacswiki.org/emacs/BrowseUrl#toc17

If you want to use xwidgets just for maple-preview, use
```
(defun maple-preview:open-browser ()
  "Open browser."
  (let ((browse-url-browser-function 'xwidget-webkit-browse-url))
    (browse-url
     (format "http://%s:%s/preview" maple-preview:host maple-preview:port))))
```
Well, the code has not been tested beacuse my emacs doesn't support xwidgets.

**Comment by fbob** [comment]
Many thanks for your very quick and helpful feedback.
Will test the code as soon as I can.
You've made an excellent package, THANKS :)

**Comment by fbob** [comment]
Great, it works but xwidgets is very flickery for me. No problem with an external browser.
![image](https://user-images.githubusercontent.com/8211124/63207821-42058f00-c0cd-11e9-81a8-b9b565bd025d.png)
